spring.application.name=ecom
spring.datasource.url=jdbc:mysql://localhost:3306/ecomdb
spring.datasource.username=root
spring.datasource.password=Athesh2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=rded4KDeeJOqnMrJvzNjaTFqDqIWczAL8H4x1zTeUIk=